apiVersion: v1
kind: Service
metadata:
  name: java-microservice-service
spec:
  type: LoadBalancer
  selector:
    app: java-microservice
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
