apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-deployment
  labels:
    app: java-microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-microservice
  template:
    metadata:
      labels:
        app: java-microservice
    spec:
      containers:
      - name: java-microservice-container
        image: 594359759417.dkr.ecr.us-west-2.amazonaws.com/stockcharts
        ports:
        - containerPort: 8080
