apiVersion: apps/v1
kind: Deployment
metadata:
  name: stockcharts-deployment
  labels:
    app: stockcharts
spec:
  selector:
    matchLabels:
      app: stockcharts
  template:
    metadata:
      labels:
        app: stockcharts
    spec:
      containers:
      - name: stockcharts-container
        image: 594359759417.dkr.ecr.us-west-2.amazonaws.com/stockcharts
        ports:
        - containerPort: 9080
---
apiVersion: v1
kind: Service
metadata:
  name: stockcharts-service
spec:
  type: NodePort
  selector:
    app: stockcharts 
  ports:
  - protocol: TCP
    port: 9080
    targetPort: 9080
    nodePort: 32000

