AWSTemplateFormatVersion : '2010-09-09'
Description : 'aws cloudformation create-stack --stack-name SpinupEC2 --template-body file://SpinupEC2.yaml'

Resources :
    DemoInstance :
        Type : 'AWS::EC2::Instance'
        Properties :
            ImageId : 'ami-08e2d37b6a0129927'
            InstanceType : 't2.micro'
            KeyName : 'mykeypair03012020'
            SubnetId : 'subnet-0cbd6edb87f588a5e'
            Tags :
                - Key : 'Name'
                  Value : 'MyDevBox'
            UserData :
                Fn::Base64:
                    !Sub |
                        #!/bin/bash
                        sudo yum -y update
                        sudo yum install -y git
                        cd /home/ec2-user
                        sudo amazon-linux-extras install -y java-openjdk11
                        sudo wget http://repos.fedorapeople.org/repos/dchen/apache-maven/epel-apache-maven.repo -O /etc/yum.repos.d/epel-apache-maven.repo
                        sudo sed -i s/\$releasever/6/g /etc/yum.repos.d/epel-apache-maven.repo
                        sudo yum install -y apache-maven
                        sudo yum install -y mysql
                        sudo yum install -y docker
                        sudo service docker restart
                        iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-ports 8080
                        echo '#!/bin/sh' > config.sh
                        echo 'export dbinstance=$1 dbname=$2 dbuserid=$3 dbpassword=$4' >> config.sh
                        echo 'mkdir java' >> config.sh
                        echo 'mkdir java/stockcharts' >> config.sh
                        echo 'cd java/stockcharts' >> config.sh
                        echo 'git clone https://github.com/anilb-cool-dev/StockCharts .' >> config.sh
                        echo 'mvn package' >> config.sh
                        echo 'sudo usermod -a -G docker $USER' >> config.sh
                        chmod a=rwx config.sh
